config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'home/index', to: 'home#index'
  root 'home#index'
  resources :subscripts, only: %i[new create index]

  namespace :api do
    namespace :v1 do
      resources :subscripts, only: [:index,:create]
    end
  end
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subscript.rb
class Subscript < ApplicationRecord
end

app/controllers/api/v1/subscripts_controller.rb
class Api::V1::SubscriptsController < ApplicationController
    def index
        render json: Subscript.all
    end

    def create
        SubscriptCreateJob.perform_later(subscript_params)
        
        render json: { message: "Inscrição Enviada com Sucesso!" }, :status => :created
    end
       
    private
       
    def subscript_params
        params.require(:subscript).permit(:name, :email, :phone, :description, :language, :schooling)
    end
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/subscripts_controller.rb
class SubscriptsController < ApplicationController
  def index
    @subscripts = Subscript.all
  end
  
  def new
    @subscript = Subscript.new
  end

  def create
    @subscript = Subscript.new(subscript_params)
    redirect_to new_subscript_path unless @subscript.save
  end

  private

  def subscript_params
    params.require(:subscript).permit(:name, :email, :phone, :description, :language, :schooling)
  end
end

app/helpers/api/v1/subscrips_helper.rb
module Api::V1::SubscripsHelper
end

app/helpers/api/v1/subscripts_helper.rb
module Api::V1::SubscriptsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscripts_helper.rb
module SubscriptsHelper
end

app/views/home/index.html.erb
<h1 id='h1'>SUPER DESENVOLVER</h1>
<h2 id='h2'>Venha fazer parte do Código dos Bons</h2>
<%= link_to "QUERO ENTRAR", new_subscript_path, id: 'button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav id="menu">
      <ul>
        <li>
          <%= link_to "Principal", root_path %>
          <a href="#">Sobre</a>
          <%= link_to "Seja Aluno", new_subscript_path %>
          <%= link_to "Alunos", subscripts_path %>
          <a href="#">Preço</a>
          <a href="#">Contato</a>
        </li>
      </ul>
    </nav>
    <div id="content">
      <%= yield %>  
    </div>

  <script>
   function typeWrite(elemento){
       const textoArray = elemento.innerHTML.split('');
       elemento.innerHTML = ' ';
       textoArray.forEach(function(letra, i){  
          
       setTimeout(function(){
           elemento.innerHTML += letra;
       }, 75 * i)
    
       });
     }
     const titulo = document.querySelector('#h2');
     typeWrite(titulo);
  </script>

  </body>
</html>

app/views/subscripts/create.html.erb
<h1 id="h1"><%= @subscript.name %></h1>
<h1 id="h1">PARABÉNS!</h1>
<h2 id="h2">Vamos juntos transformar o Brasil com a Programação!</h2>

app/views/subscripts/index.html.erb
<h1 id="h1">SUPER DESENVOLVEDORES</h1>
<h2 id="h2">Veja quem já iniciou a transformação de suas vidas!</h2>
<table id="subscripts">
 <tr>
   <th>#</th>
   <th>Nome</th>
   <th>Linguagem de Programação</th>
   <th>Escolaridade</th>
 </tr>
 <% @subscripts.each do |subscript| %>
   <tr>
     <td><%= subscript.id %></td>
     <td><%= subscript.name %></td>
     <td><%= subscript.language %></td>
     <td><%= subscript.schooling %></td>
   </tr>
 <% end %>
</table>

app/views/subscripts/new.html.erb
<h1 id="h1">INSCRIÇÃO SUPER DESENVOLVEDOR</h1>
<h2 id="h2">Seu futuro e sua família agradecem!</h2>
<div id="form">
  <%= form_for @subscript do |f| %>
   <%= f.text_field :name, placeholder: "Nome" %><br />
   <%= f.text_field :email, placeholder: "Email" %><br />
   <%= f.text_field :phone, placeholder: "Telefone" %><br />
   <%= f.text_area :description, placeholder: "Descrição" %><br />
   <%= f.select :language, ["Javascript", "Python", "Java", "Php", "Ruby"], include_blank: "Linguagem" %><br />
   <%= f.select :schooling, ["Fundamental", "Médio", "Superior Incompleto", "Superior Completo"], include_blank: "Escolaridade" %><br />
   <%= f.submit "Enviar"%>
  <% end %>
</div>